<?php
/**
 * Payment form
 *
 * @package         Apptha PayPal Adaptive
 * @version         0.1.1
 * @since           Magento 1.5
 * @author          Apptha Team
 * @copyright       Copyright (C) 2014 Powered by Apptha
 * @license         http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date   January 02,2014
 * @Modified By     Ramkumar M
 * @Modified Date   January 02,2014
 *
 * */
/*
 * Initilize payment code and description
 */
$_code = $this->getMethodCode();
$description = Mage::helper('paypaladaptive')->getPaymentDescription();
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">    
    <?php
    if (!empty($description)) {
        /*
         * If checking whether description available or not
         */
        ?>
        <li> <?php echo $description; ?> </li>    
    <?php
    }
    /*
     * End if for checking whether description available or not 
     */
    ?> 
    <li><?php echo $this->__('You will be redirected to the Paypal Checkout website when you place an order.') ?></li>
</ul>