<?php
/*$arr=array();
$arr=$this->getFormData();
print_r($arr);*/
//exit;
?>

<b><?php echo Mage::helper('paytm')->__('You will be redirected to Paytm Payment Gateway in a few seconds.'); ?></b>
<form name="paytm_checkout" id="paytm_checkout" action="<?php echo $this->getFormAction();?>" method="POST">
<?php $arr  = array();
$arr = $this->getFormData();?>
<?php if (is_array($arr)): ?>
    <?php foreach ($arr as $name => $value): ?>
    	
    	<?php mage::log($name .'=>'. $value,null,'paytm_test.log'); ?>

        <input type="hidden" name="<?php echo $name; ?>" <?php if (!is_null($value)) { echo 'value="'. $value . '"'; } ?> />
    <?php endforeach; ?>
<?php endif; ?>

</form>
<?php //print_r($arr);exit;?>
<script type="text/javascript">
//<![CDATA[
    var paymentform = document.getElementById('paytm_checkout');
    window.onload = paymentform.submit();
//]]>
</script>